# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  web:
    build:
      context: .  
      dockerfile: infrastructure/docker/Dockerfile  
    ports:
      - "1036:80"  
