services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    env_file: .env
    healthcheck:
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 3s

    ports:
      - ${SERVER_PORT}:80
